name: Publish
on:
  release:
    types:
      - published
permissions:
    contents: write
    id-token: write
jobs:
  publish:
    strategy:
      matrix:
        os:
          - linux
        arch:
          - amd64
          - arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: go build -o bin/jobloader-${{ matrix.os }}-${{ matrix.arch }}
             -ldflags "-X github.com/brandond/jobloader/pkg/version/GitVersion=${{ github.ref_type == 'tag' && github.ref_name || 'dev' }} -X github.com/brandond/jobloader/pkg/version/GitCommit=${{ github.sha }}" \
             -extldflags "-static -lm -ldl -lz -lpthread"
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Upload Release Assets
        run: gh release upload ${{ github.ref_name }} bin/*
        env:
          GH_TOKEN: ${{ github.token }}
